name = "xl-vidio-sofyan" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
routes = [
  { pattern = "sg1.sofyanekafebriyanto.my.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.sofyanekafebriyanto.my.id", custom_domain = true },
  { pattern = "quiz.vidio.com.sofyanekafebriyanto.my.id", custom_domain = true }
]

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "10ccd380-ff9f-4ace-9df9-3da5b830728d"
